### ISSUE TITLE
Connection to office.runtimeverification refused

### ISSUE THREAD

**Issue by SebastienGllmt** [kframework/javascript-semantics#3]
Connection to http://office.runtimeverification.com:8888 refused: Connection refused (Connection refused)

In the past this seems to have been fixed by @dwightguth

**Comment by grosu** [comment]
@daejunpark see @SebastienGllmt 's comment above.

**Comment by daejunpark** [comment]
@SebastienGllmt Could you try to change the URL in the pom.xml?

from
```<url>http://office.runtimeverification.com:8888/repository/internal</url>```
to
```<url>https://s3.amazonaws.com/repo.runtime.verification/repository/internal</url>```

and 

from
```<url>http://office.runtimeverification.com:8888/repository/snapshots</url>```
to
```<url>https://s3.amazonaws.com/repo.runtime.verification/repository/snapshots</url>```

**Comment by SebastienGllmt** [comment]
@daejunpark That fixed it. Thanks!
